# fly.toml app configuration file generated for class-interactor on 2023-07-10T19:11:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "class-interactor"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    soft_limit = 400
    hard_limit = 500

[deploy]
  strategy = "rolling"