name: Continuous integration pipeline
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  HUSKY: 0
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "pnpm"
      - name: Pull test docker images
        shell: bash
        run: |
          for each in {"postgres:15","testcontainers/ryuk:0.5.1"}; do docker pull "$each"; done
      - name: npm install, test, lint and build
        run: |
          pnpm install
          pnpm run test:ci
          pnpm run lint
          pnpm run build
      
  
